### ISSUE TITLE
Implement Event Creation Page

### ISSUE THREAD

**Issue by gionare** [beqa200/colab-team4#4]
### Task: Implement Event Creation Page

**Objective:**
Create a page where users can input the details to create a new event, such as event name, description, date, time, location, and the number of attendees.

### Requirements:
- Provide input fields for the following event details:
  - Event Name (required)
  - Description (optional)
  - Date (required)
  - Time (required)
  - Location (integrate Google Maps API for location selection)
  - Maximum number of attendees (optional)
- Include a button to save the event and validate that the required fields are filled.
- Add an option to invite participants (through email or username).
- After saving, redirect the user to the **Dashboard Page** to view the created event.
- Provide a button for canceling event creation that takes the user back to the **Dashboard**.

### Additional Features:
- Use a date and time picker for selecting event date and time.
- Include a map feature for users to choose a location using Google Maps API.
- Display real-time validation for required fields.
- Add responsive design for both mobile and desktop views.

### Design Considerations:
- Ensure a clean, intuitive UI for event creation.
- Use form validation to ensure the event has all the necessary information.
- Provide feedback to the user if an error occurs during the event creation process.

### Dependencies:
- Backend API to create a new event and store event details.
- Google Maps API for selecting event location.

### Checklist:
- [ ] Create form layout with required input fields
- [ ] Add real-time validation for required fields
- [ ] Integrate Google Maps API for location selection
- [ ] Add save and cancel buttons with appropriate functionality
- [ ] Redirect the user to the dashboard after saving the event
- [ ] Integrate backend API to store the new event
- [ ] Ensure responsive design using Tailwind CSS

**Comment by gionare** [comment]
Data to Send (Create/Edit Event)

Create Event:
{
  "title": "Event Title",
  "description": "Event Description",
  "date": "2024-10-15T14:00:00Z",
  "location": "123 Event St, City",
  "maxAttendees": 100
}

Edit Event:
{
  "id": "eventId",
  "title": "Updated Event Title",
  "description": "Updated Description",
  "date": "2024-10-15T14:00:00Z",
  "location": "123 Event St, City",
  "maxAttendees": 150
}

Data to Receive

Response (for Create/Edit):
{
  "id": "eventId",
  "title": "Event Title",
  "description": "Event Description",
  "date": "2024-10-15T14:00:00Z",
  "location": "123 Event St, City",
  "maxAttendees": 100,
  "createdBy": "userId",
  "participants": []
}

Types

interface Event {
  id: string;
  title: string;
  description: string;
  date: string; // ISO string
  location: string;
  maxAttendees: number;
  createdBy: string;
  participants: string[]; // List of user IDs
}

interface CreateEventRequest {
  title: string;
  description: string;
  date: string;
  location: string;
  maxAttendees: number;
}

interface EditEventRequest extends CreateEventRequest {
  id: string;
}
